### ISSUE TITLE
Write up for this work

### ISSUE THREAD

**Issue by Mingyuan1997** [inquire-benchmark/INQUIRE#1]
Thanks for your great work and efforts in making it public. Is there any write-up for this work available either in some venues or arxiv?

Thanks!

**Comment by evendrow** [comment]
Hey, thank you for your interest! Yes, we'll be releasing the paper within a couple weeks. INQUIRE was also recently accepted to NeurIPS 2024.

**Comment by Mingyuan1997** [comment]
Congratulations! I’m looking forward to reading your paper in a couple of weeks, especially interested in the evaluation metrics and ground truth you used for the retrieval task.

Best

**Comment by evendrow** [comment]
Hi, please find the paper here: https://arxiv.org/abs/2411.02537
